DELETE http://localhost:8080/events/6
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF5YW5AZXhhbXBsZTMuY29tIiwiZXhwIjoxNzY4MTUzMjg4LCJ1c2VySWQiOjN9.8h5dy3_H4C66WhwUtoQjRKB7-4wau84339A4UeYirSg